datagrids:
  aaxis-training-test-grid:
    extended_entity_name: 'AAXIS\Bundle\TrainingBundle\Entity\Test'
    options:
      entity_pagination: true
    source:
      type: orm
      query:
        select:
          - DISTINCT test1.id
          - test1.name
          - test_type.name as type
        from:
          - { table: 'AAXIS\Bundle\TrainingBundle\Entity\Test', alias: test1 }
        join:
          left:
            - join: 'AAXIS\Bundle\TrainingBundle\Entity\TestTypeAttr'
              alias: test_type
              conditionType: WITH
              condition: 'test1.type = test_type.id'
    columns:
      name:
        label: aaxis.training.test.name
      type:
        label: aaxis.training.test.test_type_attr
    properties:
      id: ~
      update_link:
        type: url
        route: aaxis_training_test_update
        params:
          - id
    actions:
      edit:
        type: navigate
        label: Edit
        link: update_link
        icon: edit

