datagrids:
  aaxis-training-test-grid:
    options:
      entity_pagination: true
    source:
      type: orm
      query:
        select:
          - DISTINCT test1.id
          - test1.name
          - type.name
        from:
          - { table: 'AAXIS\Bundle\TrainingBundle\Entity\Test', alias: test1 }
        join:
          left:
            - join: 'AAXIS\Bundle\TrainingBundle\Entity\TestTypeAttr'
              alias: type
              conditionType: WITH
              condition: 'type.id = test1.type_id'
    properties:
      id: ~
      update_link:
        type: url
        route: aaxis_training_test_update
        params:
          - id
    actions:
      edit:
        type: navigate
        label: Edit
        link: update_link
        icon: edit

